#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
cd $OPENSHIFT_REPO_DIR

if [[ ! -x "gradlew" ]]; then
	chmod u+x gradlew
fi

nohup ./gradlew build > output.log 2> err.log < /dev/null & 
