#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
cd $OPENSHIFT_REPO_DIR
export GRADLE_USER_HOME=$OPENSHIFT_DATA_DIR/gradle

if [[ ! -x "gradlew" ]]; then
	chmod u+x gradlew
fi

nohup ./gradlew -Dorg.gradle.bindaddress=$OPENSHIFT_INTERNAL_IP build > $OPENSHIFT_LOG_DIR/gradle_output.log 2> $OPENSHIFT_LOG_DIR/gradle_err.log < /dev/null & 
